services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      PORT: 3001
      CLIENT_URL: https://qwalyyyy.popovichab.ru
    expose:
      - "127.0.0.1:3001:3001"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "127.0.0.1:8080:80"
    depends_on:
      - backend
    restart: unless-stopped
